# Generated by Django 5.1 on 2024-08-31 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('deparment', models.TextField(max_length=200)),
                ('banner', models.ImageField(blank=True, default='fallback.png', upload_to='category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('item', models.TextField(max_length=200)),
                ('banner', models.ImageField(blank=True, default='fallback.png', upload_to='uploads/product/')),
                ('product_description', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(default='+234 (000) 678', max_length=100)),
                ('price', models.IntegerField(default='0.00')),
                ('shipping_time', models.FloatField(default='very fast', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jumia.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.TextField(max_length=200)),
                ('banner', models.ImageField(blank=True, default='fallback.png', upload_to='user_directory_path')),
                ('address', models.CharField(default='Nigeria', max_length=100)),
                ('bio', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(default='+234 (000) 678', max_length=100)),
                ('response_duration', models.CharField(default='typically replies within an hour', max_length=100)),
                ('shipping_time', models.FloatField(default='very fast', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'vendors',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jumia.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jumia.vendor')),
            ],
        ),
    ]
