# Generated by Django 5.1 on 2024-09-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_time',
            field=models.CharField(default='very fast', max_length=100),
        ),
    ]
