# Generated by Django 5.1 on 2024-09-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumia', '0002_alter_product_price_alter_product_shipping_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=9),
        ),
    ]
